/soft_hand/gazebo_ros_control:
  pid_gains:
    soft_hand_thumb_abd_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_thumb_inner_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_thumb_outer_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_index_abd_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_index_inner_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_index_middle_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_index_outer_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_middle_abd_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_middle_inner_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_middle_middle_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_middle_outer_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_ring_abd_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_ring_inner_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_ring_middle_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_ring_outer_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_little_abd_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_little_inner_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_little_middle_joint: {p: 100.0, i: 0.01, d: 10.0}
    soft_hand_little_outer_joint: {p: 100.0, i: 0.01, d: 10.0}

